name: Bun CI

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

env:
  ANTHROPIC_API_KEY: test

jobs:
  test:
    name: Bun Tests
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: oven-sh/setup-bun@v1
      - run: bun install
      - run: bun test
